### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by maiermic** [vardius/peer-data#9]
I'm not sure, if the npm package is supposed to be usable as JavaScript module, but if I use

```html
<script type="module" src="node_modules/peer-data/dist/index.es.js"></script>
```

I get

```
Uncaught ReferenceError: require is not definedat SocketChannel.ts:5
```

Is [this](https://github.com/vardius/peer-data/blob/edde63c468d1e1a0c912c475a8d7d7e7f5f29083/src/app/SocketChannel.ts#L5) a bug or do I misunderstand how `index.es.js` is supposed to be used? :sweat_smile:

**Comment by vardius** [comment]
Hey man thanks for letting me know, the issue was due to mixing import with require 

I fixed it here: https://github.com/vardius/peer-data/commit/8be94e8605d53c38a11b188fd524e5d170778650
and released a new version https://github.com/vardius/peer-data/releases/tag/v3.1.8
please let me know if this works for you, I did not test this release.

**Comment by vardius** [comment]
I tested on a new release, with a little change (removed global instance of event dispatcher)
seems to work fine https://github.com/vardius/peer-data/releases/tag/v3.2.1

**Comment by maiermic** [comment]
Thanks, seems to work :+1:
